
#+TITLE: Список научных трудов

* Назначение

Страница предназначена для огранизации всего моего списка научных
трудов в формах документа для ВАК и простого списка.

* Организация

** Страница

Структура страницы:
- заголовок
- форма управления
- ссылки на мои другие страницы
- список трудов
- подпись автора
- ссылка на страницу

В верхней части страницы находится форма, которая позволяет управлять
списком.  Форма содержит:
- выбор формы (библиография, ВАК)
- числовое поле год начала
- числовое поле год конца
- группа соавторов?
- группа типов публикаций
- отметка ссылок на другие мои страницы

В режиме страницы не отображается подпись автора внизу.

В режиме печати не отображается форма управления и ссылки в
библиографическом виде после каждой статьи.  Но при этом отображается
ссылка на страницу.

Все настройки формы передаются в строку запроса GET, чтобы можно было
делиться страницей с определенными настройками.  Из строки GET
настройки попадают в скрипт, где обрабатываются дальше.

Список статей генерируется из структуры данных отдельным скриптом.

