
#+TITLE: Список научных трудов

* Назначение

Страница предназначена для огранизации всего моего списка научных
трудов в формах документа для ВАК и простого списка.

* Организация

** Страница

Структура страницы:
- заголовок
- форма управления
- ссылки на мои другие страницы
- список трудов
- подпись автора
- ссылка на страницу

В верхней части страницы находится форма, которая позволяет управлять
списком.  Форма содержит:
- выбор формы (библиография, ВАК)
- числовое поле год начала
- числовое поле год конца
- группа соавторов?
- группа типов публикаций
- отметка ссылок на другие мои страницы

В режиме страницы не отображается подпись автора внизу.

В режиме печати не отображается форма управления и ссылки в
библиографическом виде после каждой статьи.  Но при этом отображается
ссылка на страницу.

Все настройки формы передаются в строку запроса GET, чтобы можно было
делиться страницей с определенными настройками.  Из строки GET
настройки попадают в скрипт, где обрабатываются дальше.

Список статей генерируется из структуры данных отдельным скриптом.


* Функция для отображения

Функция для отображения списка (в форме ~p~ или ~tr~) принимает на
вход фильтры:
#+begin_src js
  {
      "filter": {
	  "years": {
	      "start": 2011,
	      "end": 2022,
	  },
	  "type": false,
	  "keywords": false,
	  "coauthors": false,
	  "languages": false
      }
  }
#+end_src

Фильтр работает по типу И.  Запись должна отвечать всем фильтрам,
иначе она будет исключена.  Каждый фильтр выбирает только один из
вариантов.

Эта же функция принимает на вход информацию для отображения:
#+begin_src js
  {
      "display": {
	  "keywords": true,
	  "links": true,
	  "group": {
	      "base": "types",
	      "show": false
	  }
      }
  }
#+end_src

Когда группировка выполняется по типам, то сортировка выполняется по
годам, когда группировка выполняется по годам, то сортировка
выполняется по типам.

Когда выполняется группировка, внутри групп подсчитывается количество
трудов и страниц.
